services:
  - type: web
    name: vault-tracker-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    envVars:
      - key: PORT
        value: 5000

  - type: web
    name: vault-tracker-frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://vault-tracker-backend.onrender.com
